Steunijos.WebUI/Controllers/ContactUsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Steunijos.Domain.DomainModels;
using Steunijos.WebUI.Data;
using Steunijos.WebUI.ViewModels.ContactUs;

namespace Steunijos.WebUI.Controllers
{
    public class ContactUsController : Controller
    {
        private readonly IConfiguration _config;
        private readonly SteunijosContext _db;

        public ContactUsController(IConfiguration config, SteunijosContext db)
        {
            _config = config;
            _db = db;
        }
        // GET: Contact
        public async Task<ActionResult> Index()
        {
            //get all correspondence sent successfully and show it here.
            var result = await _db.ContactUsSubmissions.AsNoTracking()
                .Select(c => new ContactUsViewModel
                {
                    EmailAddress = c.SendersEmail,
                    FullName = c.SendersFullName,
                    MessageType = c.MessageType,
                    SubmissionDate = c.SubmissionDate,
                    SubmissionId = c.Id,
                    SubmittedMessage = c.MessageSent
                }).ToListAsync().ConfigureAwait(false);
            return View(result);
        }

        // GET: Contact/Details/5
        public async Task<ActionResult> Details(int id, CancellationToken token)
        {
            //show the message sent by its id
            var details = await _db.ContactUsSubmissions.AsNoTracking()
                .Where(x => x.Id.Equals(id))
                .Select(c => new ContactUsDetailModel
                {
                    EmailAddress = c.SendersEmail,
                    FullName = c.SendersFullName,
                    MessageType = c.MessageType,
                    SubmissionDate = c.SubmissionDate,
                    SubmissionId = c.Id,
                    SubmittedMessage = c.MessageSent
                }).SingleOrDefaultAsync(token).ConfigureAwait(false);

            return View(details);
        }

        // GET: Contact/Create
        public ActionResult Create()
        {
            var contactInput = new ContactUsInputModel();
            return View(contactInput);
        }

        // POST: Contact/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SendContact(ContactUsInputModel sent)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var username = _config.GetValue<string>("Gmail:Username");
                    var password = _config.GetValue<string>("Gmail:Password");
                    var client = new SmtpClient
                    {
                        Host = _config.GetValue<string>("Gmail:Host"),
                        Port = _config.GetValue<int>("Gmail:Port"),
                        EnableSsl = bool.Parse(_config["Gmail:SMTP:starttls:enable"]),
                        Credentials = new NetworkCredential(username, password)
                    };

                    var mail = new MailMessage(sent.EmailAddress, username)
                    {
                        Subject = sent.MessageType.ToString(),
                        Body = sent.Message,
                        IsBodyHtml = true
                    };

                    client.Send(mail);

                    var contactSubmit = new ContactUsSubmission
                    {
                        MessageSent = sent.Message,
                        MessageSubject = sent.MessageType.ToString(),
                        MessageType = sent.MessageType.ToString(),
                        SendersEmail = sent.EmailAddress,
                        SubmissionDate = DateTimeOffset.UtcNow.LocalDateTime,
                        ReceivingEmailAddress = username,
                        SendersFullName = sent.FullName,
                    };
                    _db.ContactUsSubmissions.Add(contactSubmit);
                    await _db.SaveChangesAsync();
                }
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View("Create");
            }

        }
    }
}

Steunijos.WebUI/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="it">
    <meta name="keywords" content="Rapoo,creative, agency, startup, Mobicon,onepage, clean, modern,business, company,it">
    <meta name="google-signin-client_id" content="124216463781-sslk5o9gv0hp0nirama5ddgs08qfsn8a.apps.googleusercontent.com">

    <!-- Plugins CSS -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/Pe-icon-7-stroke.css">

    <link rel="stylesheet" href="~/css/slick.css">
    <link rel="stylesheet" href="~/css/slick-theme.css">
    <link rel="stylesheet" href="~/css/all.css">

    <!-- Theme CSS -->
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/responsive.css">

    <title>Department Of Science & Technology Education</title>
</head>


<body class="top-header">

    <!-- LOADER TEMPLATE -->
    <div id="page-loader">
        <div class="loader-icon fa fa-spin colored-border"></div>
    </div>
    <!-- LOADER TEMPLATE -->
    <!-- NAVBAR
    ================================================= -->
    <nav class="navbar navbar-expand-lg navbar-dark trans-navigation fixed-top navbar-togglable">
        <div class="container">
            <a asp-controller="Home" class="navbar-brand" asp-action="Index" id="brand">
                <div class="headerContainer">
                    <div class="headerlogo-left">
                        <img src="~/img/steunijos-logo-small.png" id="logoImg" />
                    </div>
                </div>
            </a>
            <!-- Toggler -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="fa fa-bars"></span>
            </button>

            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <!-- Links -->
                <ul class="navbar-nav ml-auto">

                    <li class="nav-item ">
                        <a asp-controller="Home" asp-action="Index" class="nav-link js-scroll-trigger">
                            Home
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a asp-controller="Journals" asp-action="Create" class="nav-link js-scroll-trigger">
                            Journals
                        </a>
                    </li>

                    <li class="nav-item ">
                        <a asp-controller="Papers" asp-action="SubmitPaper" class="nav-link js-scroll-trigger">
                            Papers
                        </a>
                    </li>

                    <li class="nav-item ">
                        <a asp-controller="Editors" asp-action="Index" class="nav-link">
                            Editors
                        </a>
                    </li>

                    <li class="nav-item ">
                        <a asp-controller="ContactUs" asp-action="Create" class="nav-link">
                            ContactUs
                        </a>
                    </li>
                    <li></li>
                    <li></li>
                    <partial name="_LoginPartial" />
                </ul>
            </div> <!-- / .navbar-collapse -->
        </div> <!-- / .container -->
    </nav>

    @RenderBody()


    <!-- FOOTER
    ================================================== -->
    <footer class="section " id="footer">
        <div class="overlay footer-overlay"></div>
        <!--Content -->
        <div class="container">
            <div class="row justify-content-start">
                <div class="col-lg-4 col-sm-12">
                    <div class="footer-widget">
                        <!-- Brand -->
                        <a href="#" class="footer-brand text-white">
                            Department of Science & Technology Education, University of Jos.
                        </a>
                    </div>
                </div>

                <div class="col-lg-3 ml-lg-auto col-sm-12">
                    <div class="footer-widget">
                        <h3>Account</h3>
                        <!-- Links -->
                        <ul class="footer-links ">

                            <li>
                                <a href="#">
                                    Help and support
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Frequently Asked Question
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>


                <div class="col-lg-2 col-sm-6">
                    <div class="footer-widget">
                        <h3>About</h3>
                        <!-- Links -->
                        <ul class="footer-links ">

                            <li>
                                <a href="#">
                                    About Us
                                </a>
                            </li>

                            <li>
                                <a href="#">
                                    Contact
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-2 col-sm-6">
                    <div class="footer-widget">
                        <h3>Socials</h3>
                        <!-- Links -->
                        <ul class="list-unstyled footer-links">
                        </ul>
                    </div>
                </div>
            </div> <!-- / .row -->


            <div class="row text-right pt-5">
                <div class="col-lg-12">
                    <!-- Copyright -->
                    <p class="footer-copy ">
                        &copy; Copyright <b class="current-year"> @DateTimeOffset.Now.Year </b> All rights reserved.
                    </p>
                </div>
            </div> <!-- / .row -->
        </div> <!-- / .container -->
    </footer>


    <!--  Page Scroll to Top  -->
    <a class="scroll-to-top js-scroll-trigger" href=".top-header">
        <i class="fa fa-angle-up"></i>
    </a>

    <!-- JAVASCRIPT
    ================================================== -->
    <!-- Global JS -->
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>

    <!-- Plugins JS -->
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>

    <!-- Slick JS -->
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/slick.min.js"></script>
    <!-- Theme JS -->
    <script src="~/js/theme.js"></script>

    @RenderSection("Scripts", required: false)


</body>

</html>